<?php
return array(
	'_root_' => 'loja/produtos/',  // The default route
	'_404_'  => 'main/404',   
	'adm' 	 => 'adm/pedidos',		
	'postagens/(:post_url)' 	=>'loja/postagens/postagem',
	'postagens' 				=>'loja/postagens',	
	'quem-somos' 				=>'loja/institucional/quem_somos',
	'como-comprar' 				=>'loja/institucional/como_comprar',
	'duvidas-frequentes' 		=>'loja/duvidas/index',
	'contato' 					=>'loja/contato/index',
	'contato/enviar' 			=>'loja/contato/enviar',
	'produtos' 					=>'loja/produtos/index',
	'produtos/busca' 			=>'loja/produtos/busca',	
	'produtos/(:categoria)/(:produto)' =>'loja/produtos/produto',
	'produtos/(:categoria)' 		   =>'loja/produtos/index',
	'carrinho' 		  				   =>'loja/carrinho/index',
	'carrinho/tax' 		  		   	   =>'loja/carrinho/tax',
	'carrinho/update' 		  		   =>'loja/carrinho/update',
	'carrinho/paypal' 		  		   =>'loja/carrinho/paypal',
	'carrinho/paypal-revision' 		   =>'loja/carrinho/paypal_revision',
	'carrinho/paypal-confirm' 		   =>'loja/carrinho/paypal_confirm',
	'carrinho/paypay-notify' 		   =>'loja/carrinho/paypal_notify',		
	'carrinho/add/(:produto)' 		   =>'loja/carrinho/add',
	'carrinho/remove/(:produto)' 	   =>'loja/carrinho/remove',
	'conta'							=>'loja/conta/index',
	'conta/entrar'					=>'loja/conta/entrar',
	'conta/cadastrar'				=>'loja/conta/cadastrar',
	'conta/pedidos'					=>'loja/conta/pedidos',
	'conta/pedidos/detalhes/(:id)'	=>'loja/conta/pedido',
	'conta/sair'					=>'loja/conta/sair',
	'conta/perfil'					=>'loja/conta/perfil',
	'conta/lembrar-senha'			=>'loja/conta/lembrar',
);